import jsPDF from 'jspdf';
import { GrWithDelivery } from '../types/gr';

export class PDFGenerator {
  static generateGR(gr: GrWithDelivery): void {
    const doc = new jsPDF();

    // Set up colors and fonts
    const primaryColor: [number, number, number] = [41, 128, 185]; // Blue
    const secondaryColor: [number, number, number] = [52, 73, 94]; // Dark gray
    const accentColor: [number, number, number] = [46, 204, 113]; // Green

    // Header
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 30, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text('Cylinder Management System', 105, 15, { align: 'center' });

    doc.setFontSize(16);
    doc.text('Goods Receipt (GR)', 105, 25, { align: 'center' });

    // GR Details Box
    doc.setFillColor(248, 249, 250);
    doc.rect(10, 40, 190, 40, 'F');

    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.setFontSize(14);
    doc.text('GR Details', 15, 50);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);

    // GR Information
    const grInfo = [
      `GR Number: GR-${gr.gr_id}`,
      `GR Status: ${gr.gr_status}`,
      `Created Date: ${new Date(gr.created_at).toLocaleDateString()}`,
      `Advance Amount: ₹${gr.advance_amount.toFixed(2)}`
    ];

    grInfo.forEach((info, index) => {
      doc.text(info, 15, 60 + (index * 8));
    });

    // Delivery Information Box
    doc.setFillColor(248, 249, 250);
    doc.rect(10, 90, 190, 50, 'F');

    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.setFontSize(14);
    doc.text('Delivery Information', 15, 100);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);

    // Delivery Information
    const deliveryInfo = [
      `Customer: ${gr.delivery_info.customer_name}`,
      `Vehicle: ${gr.delivery_info.vehicle_number}`,
      `Driver: ${gr.delivery_info.driver_name || 'N/A'}`,
      `Delivery Date: ${new Date(gr.delivery_info.delivery_datetime).toLocaleDateString()}`,
      `Delivery Time: ${new Date(gr.delivery_info.delivery_datetime).toLocaleTimeString()}`
    ];

    deliveryInfo.forEach((info, index) => {
      doc.text(info, 15, 110 + (index * 8));
    });

    // Status Information
    doc.setFillColor(248, 249, 250);
    doc.rect(10, 150, 190, 30, 'F');

    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.setFontSize(14);
    doc.text('Status Information', 15, 160);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);

    const statusInfo = [
      `Current Status: ${gr.gr_status}`,
      gr.approved_at ? `Approved At: ${new Date(gr.approved_at).toLocaleString()}` : 'Not Approved Yet',
      gr.finalized_at ? `Finalized At: ${new Date(gr.finalized_at).toLocaleString()}` : 'Not Finalized Yet'
    ];

    statusInfo.forEach((info, index) => {
      doc.text(info, 15, 170 + (index * 8));
    });

    // Footer
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 270, 210, 20, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text('Generated by Cylinder Management System', 105, 280, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, 285, { align: 'center' });

    // Company stamp/approval section
    if (gr.gr_status === 'APPROVED' || gr.gr_status === 'FINALIZED') {
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.setFontSize(12);
      doc.text('✓ APPROVED', 150, 200);

      // Add approval signature line
      doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.line(140, 205, 180, 205);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text('Authorized Signature', 150, 210);
    }

    // Save the PDF
    doc.save(`GR-${gr.gr_id}.pdf`);
  }

  static generateDeliveryReport(deliveries: any[], grs: GrWithDelivery[]): void {
    const doc = new jsPDF();

    // Set up colors
    const primaryColor: [number, number, number] = [41, 128, 185]; // Blue
    const secondaryColor: [number, number, number] = [52, 73, 94]; // Dark gray

    // Header
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 30, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text('Cylinder Management System', 105, 15, { align: 'center' });

    doc.setFontSize(16);
    doc.text('Delivery Transaction Report', 105, 25, { align: 'center' });

    // Report Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 15, 45);
    doc.text(`Total Transactions: ${deliveries.length}`, 15, 52);
    doc.text(`GRs Created: ${grs.length}`, 15, 59);

    let yPosition = 70;

    // Summary Statistics
    doc.setFillColor(248, 249, 250);
    doc.rect(10, yPosition, 190, 25, 'F');

    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.setFontSize(12);
    doc.text('Summary Statistics', 15, yPosition + 8);

    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);

    const totalAmount = deliveries.reduce((sum, d) => sum + (d.total_bill_amount || 0), 0);
    const totalDelivered = deliveries.reduce((sum, d) => sum + (d.total_delivered_qty || 0), 0);
    const totalReturned = deliveries.reduce((sum, d) => sum + (d.total_returned_qty || 0), 0);

    const stats = [
      `Total Amount: ₹${totalAmount.toFixed(2)}`,
      `Total Delivered: ${totalDelivered} cylinders`,
      `Total Returned: ${totalReturned} cylinders`,
      `Net Quantity: ${totalDelivered - totalReturned} cylinders`
    ];

    stats.forEach((stat, index) => {
      doc.text(stat, 15, yPosition + 18 + (index * 6));
    });

    yPosition += 35;

    // Table Header
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(10, yPosition, 190, 10, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);

    const headers = ['DT ID', 'Customer', 'Vehicle', 'Amount', 'GR Status', 'Date'];
    const columnWidths = [20, 40, 30, 25, 25, 30];
    let xPos = 15;

    headers.forEach((header, index) => {
      doc.text(header, xPos, yPosition + 7);
      xPos += columnWidths[index];
    });

    yPosition += 15;

    // Table Data
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(7);

    deliveries.slice(0, 25).forEach((delivery, index) => { // Limit to 25 rows for PDF
      if (yPosition > 250) { // Start new page if needed
        doc.addPage();
        yPosition = 20;
      }

      xPos = 15;
      const gr = grs.find(g => g.delivery_id === delivery.delivery_id);

      const rowData = [
        `DT-${delivery.delivery_id}`,
        delivery.customer_name?.substring(0, 15) || '',
        delivery.vehicle_number?.substring(0, 12) || '',
        `₹${(delivery.total_bill_amount || 0).toFixed(0)}`,
        gr ? gr.gr_status : 'No GR',
        new Date(delivery.delivery_datetime).toLocaleDateString()
      ];

      rowData.forEach((data, colIndex) => {
        doc.text(data, xPos, yPosition + 5);
        xPos += columnWidths[colIndex];
      });

      // Alternate row colors
      if (index % 2 === 0) {
        doc.setFillColor(248, 249, 250);
        doc.rect(10, yPosition - 2, 190, 8, 'F');
        doc.setTextColor(0, 0, 0);
      }

      yPosition += 8;
    });

    // Footer
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 280, 210, 10, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(6);
    doc.text('Cylinder Management System - Delivery Report', 105, 285, { align: 'center' });

    // Save the PDF
    doc.save(`Delivery_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  }
}
