-- Clean up phantom cylinders from inventory system
-- This script removes artificially generated cylinders and fixes inventory counts

USE [Cylinder-Management];
GO

PRINT 'Starting phantom cylinder cleanup...';
PRINT '=====================================';

-- Check current inventory state before cleanup
SELECT 
    'BEFORE CLEANUP' as status,
    cil.cylinder_type_id,
    ctm.Capacity as cylinder_description,
    cil.location_type,
    cil.quantity,
    cil.location_reference_id,
    cil.location_reference_name,
    cil.last_updated
FROM CYLINDER_LOCATION_INVENTORY cil
JOIN CYLINDER_TYPE_MASTER ctm ON cil.cylinder_type_id = ctm.CylinderTypeId
WHERE cil.location_type = 'YARD'
ORDER BY cil.cylinder_type_id, cil.location_type;
GO

-- Identify potential phantom cylinders (cylinders with exactly 100 quantity in YARD)
-- This pattern indicates they were created by the problematic initialization script
PRINT 'Identifying potential phantom cylinders...';

SELECT 
    'POTENTIAL PHANTOM' as analysis,
    cil.cylinder_type_id,
    ctm.Capacity as cylinder_description,
    cil.quantity,
    cil.last_updated,
    CASE 
        WHEN cil.quantity = 100 THEN 'Likely phantom (100 units)'
        WHEN cil.quantity > 50 THEN 'Possible phantom (high count)'
        ELSE 'Manual entry (low count)'
    END as risk_level
FROM CYLINDER_LOCATION_INVENTORY cil
JOIN CYLINDER_TYPE_MASTER ctm ON cil.cylinder_type_id = ctm.CylinderTypeId
WHERE cil.location_type = 'YARD'
  AND cil.quantity = 100
ORDER BY cil.cylinder_type_id;
GO

-- Create a backup of current inventory before making changes
PRINT 'Creating backup of current inventory...';

SELECT *
INTO #INVENTORY_BACKUP_' + REPLACE(REPLACE(CONVERT(varchar, GETDATE(), 120), '-', ''), ':', '') + '_BEFORE_CLEANUP
FROM CYLINDER_LOCATION_INVENTORY;

PRINT 'Inventory backup created in temp table';
GO

-- WARNING: This will remove phantom cylinders
-- Uncomment the following lines ONLY after reviewing the above analysis

/*
PRINT 'Removing phantom cylinders (100-unit batches in YARD)...';

DELETE FROM CYLINDER_LOCATION_INVENTORY
WHERE location_type = 'YARD'
  AND quantity = 100
  AND cylinder_type_id IN (
    SELECT cylinder_type_id 
    FROM CYLINDER_LOCATION_INVENTORY 
    WHERE location_type = 'YARD' 
      AND quantity = 100
  );

PRINT 'Phantom cylinders removed';
GO

-- Log the cleanup action
INSERT INTO CYLINDER_MOVEMENT_LOG (
    cylinder_type_id,
    from_location_type,
    from_location_reference_id,
    to_location_type,
    to_location_reference_id,
    quantity,
    movement_type,
    reference_transaction_id,
    moved_by,
    movement_date,
    notes
)
SELECT 
    cylinder_type_id,
    'YARD' as from_location_type,
    location_reference_id,
    'SYSTEM' as to_location_type,
    NULL as to_location_reference_id,
    quantity,
    'PHANTOM_CLEANUP' as movement_type,
    NULL as reference_transaction_id,
    1 as moved_by,
    GETDATE() as movement_date,
    'Removed phantom cylinders generated by initialization script' as notes
FROM CYLINDER_LOCATION_INVENTORY
WHERE location_type = 'YARD'
  AND quantity = 100;

PRINT 'Cleanup logged in movement history';
GO
*/

-- Show inventory state after cleanup (when cleanup is enabled)
PRINT 'Inventory state after cleanup:';

SELECT 
    'AFTER CLEANUP' as status,
    cil.cylinder_type_id,
    ctm.Capacity as cylinder_description,
    cil.location_type,
    cil.quantity,
    cil.location_reference_id,
    cil.location_reference_name,
    cil.last_updated
FROM CYLINDER_LOCATION_INVENTORY cil
JOIN CYLINDER_TYPE_MASTER ctm ON cil.cylinder_type_id = ctm.CylinderTypeId
WHERE cil.location_type = 'YARD'
ORDER BY cil.cylinder_type_id, cil.location_type;
GO

-- Summary report
PRINT 'Cleanup Summary:';
PRINT '================';

SELECT 
    'SUMMARY' as report_type,
    COUNT(*) as total_yard_records,
    SUM(CASE WHEN quantity = 100 THEN 1 ELSE 0 END) as phantom_count,
    SUM(CASE WHEN quantity != 100 THEN 1 ELSE 0 END) as valid_count,
    SUM(quantity) as total_cylinders_in_yard
FROM CYLINDER_LOCATION_INVENTORY 
WHERE location_type = 'YARD';
GO

PRINT '=====================================';
PRINT 'Phantom cylinder cleanup script completed!';
PRINT '';
PRINT 'IMPORTANT: Review the analysis above before uncommenting the DELETE statements.';
PRINT 'Manual verification of physical inventory is recommended before cleanup.';
GO
